### ISSUE TITLE
Fiil T1 Pro Missing?

### ISSUE THREAD

**Issue by RodGuiamoy** [Kiwironic/FIILEng#2]
I was able to see Fiil T1 Pro and use it before, but when I reinstall the app it seems to be gone
![393305875_363476276034536_7312245603481877833_n](https://github.com/Kiwironic/FIILEng/assets/55446874/823fac0b-0f62-47c0-a91e-90e3faaf6c2e)
![393513495_1542758806262203_8667883901366727764_n](https://github.com/Kiwironic/FIILEng/assets/55446874/2f220f0f-22e0-40d2-b3b4-51f5d541a45f)

**Comment by RodGuiamoy** [comment]
Looks like even if it's not on the list, when you connect to the device, it will go to the Fiil T1 Pro UI.

**Comment by Kiwironic** [comment]
You are correct. Also, I cannot change the app functionality, only text and some images.
